org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


minecraft_version=1.21.3
minecraft_version_range=[1.21.3,1.21.4)
forge_version=53.1.10
forge_version_range=[53.1.10,54)
loader_version_range=[53,54)
mapping_channel=official
mapping_version=1.21.3


mod_id=imherobrine
mod_name=I'm Herobrine
mod_license=All Rights Reserved
mod_version=1.0.4
mod_group_id=com.imherobrine
mod_authors=anticreepermc
mod_description=Become a Herobrine
